### ISSUE TITLE
We cannot import it

### ISSUE THREAD

**Issue by mugenishere** [kamikaze/webdav#3]
Trying to import this module as:

```
import python_webdav
#or 
from python_webdav import client
#or 
from python_webdav import Client
```

All of these methods give the following error:

**ImportError: No module named myapp**

I installed this module using "pip install python_webdav".

**Comment by mugenishere** [comment]
Never mind! This works fine! 

I was using Pycharms which uses its own local installation of python that was constantly missing the installed packages.

I went to project settings> python interpretor and changed it to the python that was installed in the windows path. It got detected after that.

**Comment by kamikaze** [comment]
what is python_webdav o_O ? package name is webdav

**Comment by mugenishere** [comment]
whoops! I did try with webdav too and it wasn't working. Sorry, I had imported a bunch of packages. I figured out just yesterday how to use a package without any documentation.
Anyway, this is working fine. I'm closing this issue.
Also, it must feel so damn cool to have your own python package online! Maybe I'll also create something one day. ^_^
