### ISSUE TITLE
Is there any document or readme?

### ISSUE THREAD

**Issue by tobyqin** [kamikaze/webdav#4]
I cannot find it.

**Comment by kamikaze** [comment]
Hello. There is none as it is a fork. If you need one, please feel free to
fill the ticket abd specify what kind of info you are searching for )

пт, 3 мая 2019 г., 17:20 Toby Qin <notifications@github.com>:

**Comment by tobyqin** [comment]
I want a quick start guide and APIs provided by this package, great thanks.

**Comment by tobyqin** [comment]
there are some unit tests I can learn from, well thanks. 
https://github.com/kamikaze/webdav/blob/master/src/tests/test_client_it.py
